name: customers project
on:
  push:
    branches: [master]
jobs:
  Checkout:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
    Deploy:
      name: Deploy
      steps:
        - uses: amondnet/vercel-action@v20 #deploy
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
            vercel-org-id: ${{ secrets.ORG_ID}} #Required
            vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
            working-directory: ./
